Fixed steps in GettingStarted.md (#39)
* Fixed steps in GettingStarted.md

The wizard creates a subfolder that you need to `cd` into order for the steps to work. 

Without it you hit an issue: 

```zsh
MyNewProject % pwd
/Users/carlton/Projects/Swift/Hummingbird/MyNewProject
MyNewProject % ../template/configure.sh MyNewProject
Configuring your Hummingbird project
Outputting to /Users/carlton/Projects/Swift/Hummingbird/MyNewProject/MyNewProject
Enter your package name: [MyNewProject] > 
Enter your executable name: [App] > 
~/Projects/Swift/Hummingbird/template ~/Projects/Swift/Hummingbird/MyNewProject
~/Projects/Swift/Hummingbird/MyNewProject
MyNewProject % swift run App
error: Could not find Package.swift in this directory or any of its parent directories.
MyNewProject % cd MyNewProject
MyNewProject % swift run App
```

* Fixup typo

* Simplified steps.

* Update Hummingbird.docc/Articles/GettingStarted.md

---------

Co-authored-by: Adam Fowler <adamfowler71@gmail.com>